import React, { useEffect, useState } from 'react';
import { AccessPackSchema, InMemorySessionClient, type AccessPack, type LiveEvent, type SessionClient } from '../shared/contracts';
import { defaultPreferences, loadPreferences, savePreferences, type StudentPreferences } from '../shared/preferences';
import { BroadcastSessionClient, hasBroadcastChannel } from '../shared/broadcastSessionClient';
import { InstructorPanel } from '../instructor';
import { createDisplayMediaHost, type CaptureHost, type Scheduler } from '../sources/screen';
import { StudentExperience } from '../student/StudentExperience';
import reviewedBioPack from '../../../../packages/access-packs/bio-cell-demo/pack.json';
import hnswDraftPack from '../../../../packs/hnsw/pack.draft.json';
import { RoleNav, type Role } from './RoleNav';
import { ErrorBoundary } from './ErrorBoundary';

// Local demo transport: instructor and student tabs in the same browser
// profile follow each other with no network. Part 4's relay replaces it.
const defaultClient: SessionClient = hasBroadcastChannel() ? new BroadcastSessionClient() : new InMemorySessionClient();
// Constructing the host calls nothing; capture starts only from the panel's
// Start button (charter A1).
const defaultHost = createDisplayMediaHost();

/** The same page as a full browser tab. Only meaningful when running as the
 *  extension: the side panel is narrow, and a student who wants large text
 *  or the AR view needs the room. Plain tabs (the Vite preview, tests) get
 *  nothing. */
function fullTabUrl_(): string | null {
  const runtime = (globalThis as { chrome?: { runtime?: { getURL?: (path: string) => string } } }).chrome?.runtime;
  return runtime?.getURL ? runtime.getURL('index.html') : null;
}
const fullTabUrl = fullTabUrl_();

/** Packs the shell can load. `reviewed` is Part 5's internally reviewed pack;
 *  `draft` packs were generated by scripts/build-pack.ts and are not yet
 *  instructor-reviewed (charter A3), which the UI says out loud. */
export interface PackChoice { id: string; label: string; pack: AccessPack; status: 'reviewed' | 'draft'; draftPath?: string }
export const packChoices: PackChoice[] = [
  { id: 'bio-cell-demo', label: 'Cell Structure (reviewed)', pack: AccessPackSchema.parse(reviewedBioPack), status: 'reviewed' },
  { id: 'hnsw-explainer', label: 'How HNSW Works (draft)', pack: AccessPackSchema.parse(hnswDraftPack), status: 'draft', draftPath: 'packs/hnsw/pack.draft.json' },
];

interface Props {
  client?: SessionClient;
  pack?: AccessPack;
  host?: CaptureHost;
  scheduler?: Scheduler;
}

export function App({ client = defaultClient, pack, host = defaultHost, scheduler }: Props): React.ReactElement {
  const [role, setRole] = useState<Role>('instructor');
  const [event, setEvent] = useState<LiveEvent | null>(null);
  const [preferences, setPreferences] = useState<StudentPreferences>(defaultPreferences);
  const [choiceId, setChoiceId] = useState(packChoices[0].id);
  // The pack is chosen once per instructor session: the panel is keyed on it
  // so switching packs remounts the controller instead of mixing packs.
  const choice = packChoices.find(c => c.id === choiceId) ?? packChoices[0];
  const activePack = pack ?? choice.pack;
  const activeIsDraft = pack ? false : choice.status === 'draft';
  // Students never pick a pack: the session's events name the pack the
  // instructor is teaching, and the student view follows that. Until the
  // first event arrives there is nothing to render against, so any known
  // pack will do.
  const sessionPack = event ? packChoices.find(c => c.pack.packId === event.packId && c.pack.version === event.packVersion)?.pack : undefined;
  const studentPack = pack ?? sessionPack ?? choice.pack;

  useEffect(() => client.subscribe(setEvent), [client]);
  useEffect(() => { loadPreferences().then(setPreferences); }, []);

  function updatePreferences(next: StudentPreferences): void {
    setPreferences(next);
    void savePreferences(next);
  }

  return (
    <ErrorBoundary>
      <main>
        <header>
          <div>
            <h1>AccessLens</h1>
            <p>Accessible, instructor-authorized lesson sharing</p>
          </div>
          {fullTabUrl && (
            <a className="full-tab-link" href={fullTabUrl} target="_blank" rel="noopener">
              Open in a full tab
            </a>
          )}
        </header>
        <RoleNav role={role} onSelect={setRole} />
        {role === 'instructor' ? (
          <>
            {!pack && (
              <p className="pack-picker">
                <label htmlFor="pack-choice">Lesson pack</label>
                <select id="pack-choice" value={choice.id} onChange={e => setChoiceId(e.target.value)}>
                  {packChoices.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                </select>
              </p>
            )}
            {activeIsDraft && (
              <p role="note" className="draft-note">Draft pack: slide descriptions were generated by Claude and have not been instructor-reviewed yet. Review <code>{choice.draftPath}</code> before a real class.</p>
            )}
            <InstructorPanel key={activePack.packId} client={client} pack={activePack} host={host} scheduler={scheduler} />
          </>
        ) : (
          <StudentExperience
            client={client}
            event={event}
            pack={studentPack}
            preferences={preferences}
            onPreferencesChange={updatePreferences}
          />
        )}
      </main>
    </ErrorBoundary>
  );
}
