import React, { useEffect, useRef, useState } from 'react';
import { AccessPackSchema, type AccessPack, type LiveEvent, type SessionClient } from '../shared/contracts';
import { fetchPublishedPack } from '../shared/remotePack';
import { defaultPreferences, loadPreferences, savePreferences, type StudentPreferences } from '../shared/preferences';
import { CameraControl, InstructorPanel } from '../instructor';
import { AuthoringPanel } from '../instructor/AuthoringPanel';
import type { AuthoringClient, PublishedPackSummary } from '../shared/authoringClient';
import { InstructorMaterials, StudentMaterials } from '../courseMedia/CourseMaterials';
import type { ClassroomClient } from '../shared/classroomClient';
import { createDisplayMediaHost, type CaptureHost, type Scheduler } from '../sources/screen';
import { createBedrockScreenAnalyzer } from '../sources/screen/screenAnalyzer';
import { createCameraMediaHost } from '../sources/camera';
import { chromeTabs, createChromeSlidesWatcher, createSlidesOrderClient, SLIDES_READONLY_SCOPE, type SlidesSource } from '../sources/slides';
import { createExtensionAccessTokens, extensionIdentity, googleClientId } from '../shared/googleSignIn';
import { StudentExperience } from '../student/StudentExperience';
import { loadLatestLocalPack } from '../shared/localPack';
import { ReviewExperience } from '../student/ReviewExperience';
import { CourseAssistant } from '../student/CourseAssistant';
import reviewedBioPack from '../../../../packages/access-packs/bio-cell-demo/pack.json';
import { RoleNav, type Role } from './RoleNav';
import { ErrorBoundary } from './ErrorBoundary';
import { ReadingFontToggle } from './ReadingFontToggle';
import { ThemeToggle } from './ThemeToggle';
import { Wordmark } from './Wordmark';
import { createDefaultClient } from './createDefaultClient';

// Part 4's real relay when VITE_ACCESSLENS_WS_URL is configured (.env.local);
// otherwise BroadcastChannel for a same-browser demo, or in-memory.
const defaultClient: SessionClient = createDefaultClient(import.meta.env.VITE_ACCESSLENS_WS_URL);
// Constructing the host calls nothing; capture starts only from the panel's
// Start button (charter A1).
const defaultHost = createDisplayMediaHost();
const defaultAnalyzer = createBedrockScreenAnalyzer(import.meta.env.VITE_ACCESSLENS_ANALYSIS_URL);
const defaultCameraHost = createCameraMediaHost();
// Google Slides following needs the installed extension (tab URLs) and the
// Google client id (to read the deck's slide order); the hosted shell has neither.
function defaultSlidesSource(): SlidesSource | undefined {
  const tabs = chromeTabs();
  const identity = extensionIdentity();
  if (!tabs || !identity || !googleClientId) return undefined;
  const tokens = createExtensionAccessTokens(googleClientId, identity);
  return { watcher: createChromeSlidesWatcher(tabs), slideOrder: createSlidesOrderClient(() => tokens(SLIDES_READONLY_SCOPE)) };
}

/** The same page as a full browser tab. Only meaningful when running as the
 *  extension: the side panel is narrow, and a student who wants large text
 *  or the AR view needs the room. Plain tabs (the Vite preview, tests) get
 *  nothing. */
function fullTabUrl_(): string | null {
  const runtime = (globalThis as { chrome?: { runtime?: { getURL?: (path: string) => string } } }).chrome?.runtime;
  return runtime?.getURL ? `${runtime.getURL('index.html')}?surface=full` : null;
}
const fullTabUrl = fullTabUrl_();
const extensionSidePanel = fullTabUrl !== null && new URLSearchParams(window.location.search).get('surface') !== 'full';

/** Packs the shell can load. `reviewed` is Part 5's internally reviewed pack;
 *  `draft` packs were generated by scripts/build-pack.ts and are not yet
 *  instructor-reviewed (charter A3), which the UI says out loud. */
export interface PackChoice { id: string; label: string; pack: AccessPack; status: 'reviewed' | 'draft'; draftPath?: string }
export const packChoices: PackChoice[] = [
  { id: 'bio-cell-demo', label: 'Cell Structure (reviewed)', pack: AccessPackSchema.parse(reviewedBioPack), status: 'reviewed' },
];

/** Published, instructor-reviewed packs any instructor can present without
 *  signing in, fetched from the asset distribution exactly like a signed-in
 *  instructor's own. They keep demo lessons reachable where Google sign-in is
 *  not available (an origin the OAuth client does not list, T-41). */
export const publishedDemoPacks: PublishedPackSummary[] = [
  { packId: 'introduction-to-hnsw', title: 'Introduction to HNSW', version: 1, packUrl: 'packs/introduction-to-hnsw/1.json', publishedAt: '2026-09-16T18:24:16.000Z' },
];

function publishedChoiceId(pack: PublishedPackSummary): string { return `published:${pack.packId}`; }

interface Props {
  client?: SessionClient;
  pack?: AccessPack;
  /** Fetches the published pack a session names; injected in tests. */
  fetchPublishedPack?: (packId: string, version: number) => Promise<AccessPack>;
  /** The authoring API client; injected in tests, otherwise built from the Google session. */
  authoringClient?: AuthoringClient;
  /** Student class-library API client; injected in tests. */
  classroomClient?: ClassroomClient;
  host?: CaptureHost;
  cameraHost?: CaptureHost;
  scheduler?: Scheduler;
  analyzer?: import('../sources/screen/screenAnalyzer').ScreenAnalyzer;
  /** Google Slides following; defaults to the extension's tab watcher when available. */
  slides?: SlidesSource;
}

export function App({ client = defaultClient, pack, host = defaultHost, cameraHost = defaultCameraHost, scheduler, analyzer = defaultAnalyzer, fetchPublishedPack: fetchPack = fetchPublishedPack, authoringClient, classroomClient, slides = defaultSlidesSource() }: Props): React.ReactElement {
  const [role, setRole] = useState<Role>('instructor');
  const [studentSurface, setStudentSurface] = useState<'live' | 'review' | 'class' | 'materials'>('live');
  const [instructorView, setInstructorView] = useState<View>('live');
  const [event, setEvent] = useState<LiveEvent | null>(null);
  const [preferences, setPreferences] = useState<StudentPreferences>(defaultPreferences);
  const [choiceId, setChoiceId] = useState(packChoices[0].id);
  // The instructor's own published packs arrive once they sign in below. They
  // are offered next to the bundled packs; the newest is selected on arrival
  // unless the instructor already picked something, since presenting what
  // they just uploaded is why they are here.
  const [publishedPacks, setPublishedPacks] = useState<PublishedPackSummary[]>([]);
  const [instructorPack, setInstructorPack] = useState<AccessPack | null>(null);
  const [localPack, setLocalPack] = useState<AccessPack | null>(() => loadLatestLocalPack());
  const [instructorPackError, setInstructorPackError] = useState<string | null>(null);
  const picked = useRef(false);
  function pickPack(id: string): void { picked.current = true; setChoiceId(id); }
  function receivePublishedPacks(packs: PublishedPackSummary[]): void {
    setPublishedPacks(packs);
    if (!picked.current && packs.length) setChoiceId(publishedChoiceId(packs[0]));
  }
  // The pack is chosen once per instructor session: the panel is keyed on it
  // so switching packs remounts the controller instead of mixing packs.
  const choice = packChoices.find(c => c.id === choiceId) ?? packChoices[0];
  const demoPacks = publishedDemoPacks.filter(demo => !publishedPacks.some(own => own.packId === demo.packId));
  const publishedChoice = [...publishedPacks, ...demoPacks].find(p => publishedChoiceId(p) === choiceId);
  useEffect(() => {
    if (!publishedChoice) { setInstructorPack(null); setInstructorPackError(null); return; }
    let stale = false;
    setInstructorPack(null); setInstructorPackError(null);
    fetchPack(publishedChoice.packId, publishedChoice.version)
      .then(loaded => { if (!stale) setInstructorPack(loaded); })
      .catch((error: unknown) => { if (!stale) setInstructorPackError(`Could not load ${publishedChoice.title} v${publishedChoice.version}: ${error instanceof Error ? error.message : String(error)}`); });
    return () => { stale = true; };
  }, [publishedChoice, fetchPack]);
  const loadedPublished = publishedChoice && instructorPack && instructorPack.packId === publishedChoice.packId && instructorPack.version === publishedChoice.version ? instructorPack : null;
  const activePack = pack ?? localPack ?? (publishedChoice ? loadedPublished : choice.pack);
  const activeIsDraft = pack || publishedChoice ? false : choice.status === 'draft';
  // Students never pick a pack: the session's events name the pack the
  // instructor is teaching, and the student view follows that. A bundled
  // pack of that id and version is used as is; anything else is fetched from
  // the published distribution, which is where every pack the authoring
  // pipeline publishes lives. Until the first event arrives there is nothing
  // to render against, so any known pack will do.
  const [fetchedPack, setFetchedPack] = useState<AccessPack | null>(null);
  const [packError, setPackError] = useState<string | null>(null);
  const requestedPack = useRef<string | null>(null);
  const bundledPack = event ? packChoices.find(c => c.pack.packId === event.packId && c.pack.version === event.packVersion)?.pack : undefined;
  const publishedPack = event && fetchedPack && fetchedPack.packId === event.packId && fetchedPack.version === event.packVersion ? fetchedPack : undefined;
  // A student tab is commonly opened before the instructor uploads the local
  // slide. Its initial React state cannot see a later localStorage write, so
  // re-read the device-local pack when matching a live event. This keeps a
  // local preview out of the published `/packs/...` fetch path.
  const latestLocalPack = event ? loadLatestLocalPack() : null;
  const localStudentPack = event
    ? [localPack, latestLocalPack].find(candidate => candidate?.packId === event.packId && candidate?.version === event.packVersion)
    : undefined;
  const studentPack = pack ?? localStudentPack ?? bundledPack ?? publishedPack ?? choice.pack;

  useEffect(() => client.subscribe(setEvent), [client]);
  useEffect(() => {
    if (!event || pack || localStudentPack || bundledPack || publishedPack) return;
    const key = `${event.packId}@${event.packVersion}`;
    if (requestedPack.current === key) return;
    requestedPack.current = key;
    setPackError(null);
    fetchPack(event.packId, event.packVersion)
      .then(setFetchedPack)
      .catch((error: unknown) => setPackError(`Could not load the lesson pack ${event.packId} v${event.packVersion}: ${error instanceof Error ? error.message : String(error)}`));
  }, [event, pack, localStudentPack, bundledPack, publishedPack, fetchPack]);
  useEffect(() => { loadPreferences().then(setPreferences); }, []);
  // Each role has its own colours (style.css, :root[data-role]).
  useEffect(() => {
    document.documentElement.dataset.role = role;
    return () => { delete document.documentElement.dataset.role; };
  }, [role]);

  function updatePreferences(next: StudentPreferences): void {
    setPreferences(next);
    void savePreferences(next);
  }

  return (
    <ErrorBoundary>
      <main>
        <header className="masthead">
          <div className="topbar">
            <span className="mark" aria-hidden="true" />
            {/* Only the side panel needs a way out to the full tab; the full tab
                itself does not link to itself. */}
            {extensionSidePanel && fullTabUrl && (
              <a className="full-tab-link" href={fullTabUrl} target="_blank" rel="noopener">
                Open in a full tab
              </a>
            )}
            <RoleNav role={role} onSelect={setRole} />
            <div className="masthead-tools">
              <ReadingFontToggle />
              <ThemeToggle />
            </div>
          </div>
          <Wordmark />
          <p className="tagline">Accessible, instructor-authorized lesson sharing</p>
        </header>
        {role === 'instructor' ? (
          <>
            <ViewTabs label="Instructor tools" view={instructorView} onChange={setInstructorView} />
            {/* Both views stay mounted: unmounting the live panel would end
                screen sharing mid-class just to upload a file. */}
            <div id="view-panel-live" className="view-panel" role="tabpanel" aria-labelledby="view-tab-live" hidden={instructorView !== 'live'}>
              {!pack && (
                <p className="pack-picker">
                  <label htmlFor="pack-choice">Lesson pack</label>
                  <select id="pack-choice" value={publishedChoice ? publishedChoiceId(publishedChoice) : choice.id} onChange={e => pickPack(e.target.value)}>
                    {publishedPacks.length > 0 && (
                      <optgroup label="Your published packs">
                        {publishedPacks.map(p => <option key={publishedChoiceId(p)} value={publishedChoiceId(p)}>{p.title} (v{p.version})</option>)}
                      </optgroup>
                    )}
                    {demoPacks.length > 0 && (
                      <optgroup label="Published demo packs">
                        {demoPacks.map(p => <option key={publishedChoiceId(p)} value={publishedChoiceId(p)}>{p.title} (v{p.version})</option>)}
                      </optgroup>
                    )}
                    <optgroup label="Bundled demo packs">
                      {packChoices.map(c => <option key={c.id} value={c.id}>{c.label}</option>)}
                    </optgroup>
                  </select>
                  {publishedPacks.length === 0 && <span className="muted">Sign in below to present a pack you uploaded.</span>}
                </p>
              )}
              {publishedChoice && !activePack && !instructorPackError && <p role="status" aria-live="polite">Loading {publishedChoice.title}…</p>}
              {instructorPackError && <p role="alert">{instructorPackError}</p>}
              {activeIsDraft && (
                <p role="note" className="draft-note">Draft pack: slide descriptions were generated by Claude and have not been instructor-reviewed yet. Review <code>{choice.draftPath}</code> before a real class.</p>
              )}
              {activePack && <InstructorPanel key={`${activePack.packId}@${activePack.version}`} client={client} pack={activePack} host={host} scheduler={scheduler} analyzer={analyzer} slides={slides} fullTabUrl={extensionSidePanel ? fullTabUrl ?? undefined : undefined} />}
              <CameraControl host={cameraHost} />
              <AuthoringPanel client={authoringClient} onPublishedPacks={receivePublishedPacks} onLocalPack={setLocalPack} />
            </div>
            <div id="view-panel-materials" className="view-panel" role="tabpanel" aria-labelledby="view-tab-materials" hidden={instructorView !== 'materials'}>
              <InstructorMaterials />
            </div>
          </>
        ) : (
          <>
            <nav className="student-surface-nav" aria-label="Student experience">
              <button type="button" aria-current={studentSurface === 'live'} onClick={() => setStudentSurface('live')}>Live lesson</button>
              <button type="button" aria-current={studentSurface === 'review'} onClick={() => setStudentSurface('review')}>Review</button>
              <button type="button" aria-current={studentSurface === 'class'} onClick={() => setStudentSurface('class')}>Class library</button>
              <button type="button" aria-current={studentSurface === 'materials'} onClick={() => setStudentSurface('materials')}>Course materials</button>
            </nav>
            {packError && !localStudentPack && <p role="alert" className="pack-error">{packError}</p>}
            {/* The live lesson stays mounted so looking at another surface does
                not drop the student out of the session. */}
            <div hidden={studentSurface !== 'live'}>
              <StudentExperience client={client} event={event} pack={studentPack} preferences={preferences} onPreferencesChange={updatePreferences} />
            </div>
            {studentSurface === 'review' ? <ReviewExperience pack={studentPack} preferences={preferences} /> : null}
            {studentSurface === 'class' ? <CourseAssistant client={classroomClient} /> : null}
            {studentSurface === 'materials' ? <StudentMaterials /> : null}
          </>
        )}
      </main>
    </ErrorBoundary>
  );
}

type View = 'live' | 'materials';

function ViewTabs({ label, view, onChange }: { label: string; view: View; onChange: (view: View) => void }): React.ReactElement {
  return (
    <div className="mode-tabs view-tabs" role="tablist" aria-label={label}>
      <button id="view-tab-live" type="button" role="tab" aria-selected={view === 'live'} aria-controls="view-panel-live" onClick={() => onChange('live')}>Live lesson</button>
      <button id="view-tab-materials" type="button" role="tab" aria-selected={view === 'materials'} aria-controls="view-panel-materials" onClick={() => onChange('materials')}>Course materials</button>
    </div>
  );
}
