import { randomUUID } from 'node:crypto';
import { GetObjectCommand, HeadObjectCommand, ListObjectsV2Command, PutObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { GetCommand, PutCommand } from '@aws-sdk/lib-dynamodb';
import { SFNClient, StartExecutionCommand } from '@aws-sdk/client-sfn';
import {
  CreateJobRequestSchema,
  CreateUploadRequestSchema,
  HealthResponseSchema,
  JobStatusResponseSchema,
  PackVersionsResponseSchema,
  ROUTES,
} from '../shared/api';
import { JobRecordSchema } from '../shared/jobs';
import { AccessPackSchema, ArtifactManifestSchema } from '../../apps/extension/src/shared/contracts';
import { ApiHttpError, parseJsonBody, parseRequest, pathParameter, respond } from './http';
import { assetBaseUrl, artifactsBucket, decksBucket, ddb, jobsTable, packsBucket, region, s3, version } from './config';
import type { ApiEvent, ApiResult, OperationHandler } from './types';
import type { InstructorHandler } from './identity';

const route = (operationId: string) => {
  const found = ROUTES.find(candidate => candidate.operationId === operationId);
  if (!found) throw new Error(`Missing route contract for ${operationId}`);
  return found;
};

const healthRoute = route('getHealth');
const uploadRoute = route('createUpload');
const createJobRoute = route('createJob');
const getJobRoute = route('getJob');
const versionsRoute = route('listPackVersions');
const packRoute = route('getPack');
const artifactRoute = route('getArtifactManifest');

function s3ObjectKey(uploadId: string, filename: string): string {
  // Upload IDs are generated by the service and filenames are only used as a
  // suffix, so a client cannot escape the decks prefix.
  const safeName = filename.replace(/[^a-zA-Z0-9._-]/gu, '_').slice(-255);
  return `quarantine/${uploadId}/${safeName}`;
}

export const getHealth: OperationHandler = async () => respond(healthRoute, {
  ok: true,
  version,
  region,
});

export const createUpload: OperationHandler = async event => {
  const input = parseRequest(CreateUploadRequestSchema, parseJsonBody(event));
  if (!decksBucket) throw new ApiHttpError(500, 'configuration_error', 'The decks bucket is not configured.');
  const uploadId = randomUUID();
  const key = s3ObjectKey(uploadId, input.filename);
  const expiresIn = 15 * 60;
  const url = await getSignedUrl(s3, new PutObjectCommand({
    Bucket: decksBucket,
    Key: key,
    ContentType: input.contentType,
  }), { expiresIn });
  const expiresAt = new Date(Date.now() + expiresIn * 1000).toISOString();
  return respond(uploadRoute, { uploadId, url, expiresAt });
};

export const createJob: InstructorHandler = async (event, caller) => {
  const input = parseRequest(CreateJobRequestSchema, parseJsonBody(event));
  if (!jobsTable) throw new ApiHttpError(500, 'configuration_error', 'The jobs table is not configured.');

  const jobId = randomUUID();
  const now = new Date().toISOString();
  const expiresAt = Math.floor(Date.now() / 1000) + 7 * 24 * 60 * 60;
  const record = JobRecordSchema.parse({
    jobId,
    packId: input.packId,
    title: input.title,
    ...(input.description === undefined ? {} : { description: input.description }),
    ...(input.profileId === undefined ? {} : { profileId: input.profileId }),
    status: 'queued',
    uploadId: input.uploadId,
    ownerSub: caller.sub,
    createdAt: now,
    updatedAt: now,
    expiresAt,
    slides: [],
    visualHints: input.visualHints ?? [],
    reviewedAssetIds: [],
    decisions: [],
  });
  await ddb.send(new PutCommand({
    TableName: jobsTable,
    Item: record,
    ConditionExpression: 'attribute_not_exists(jobId)',
  }));

  const stateMachineArn = process.env.STATE_MACHINE_ARN;
  if (!stateMachineArn) throw new ApiHttpError(500, 'configuration_error', 'The authoring state machine is not configured.');
  const sourceKey = await resolveUploadKey(input.uploadId, input.title);
  const stateMachine = new SFNClient({ region });
  try {
    await stateMachine.send(new StartExecutionCommand({
      stateMachineArn,
      input: JSON.stringify({
        jobId,
        packId: input.packId,
        title: input.title,
        ...(input.description === undefined ? {} : { description: input.description }),
        // Always present: the workflow's retrieval Choice reads it (null
        // means no course profile, so no retrieval).
        profileId: input.profileId ?? null,
        visualHints: input.visualHints ?? [],
        uploadId: input.uploadId,
        sourceKey,
        jobsTableName: jobsTable,
        bucket: packsBucket,
        catalogBucket: process.env.CATALOG_BUCKET ?? '',
        publicBaseUrl: assetBaseUrl,
        // Every field a state machine path names must exist: undefined is
        // dropped by JSON.stringify and a missing path fails the Map state.
        instructorHint: input.visualHints?.length ? input.visualHints.map(hint => `Slide ${hint.slide}: ${hint.hint}`).join('\n') : null,
        parameters: {},
        excerpts: [],
      }),
      name: jobId,
    }));
  } catch (error) {
    await ddb.send(new PutCommand({
      TableName: jobsTable,
      Item: { ...record, status: 'failed', updatedAt: new Date().toISOString(), error: error instanceof Error ? error.message : String(error) },
    }));
    throw error;
  }
  return respond(createJobRoute, { jobId, status: record.status }, 202);
};

async function resolveUploadKey(uploadId: string, filename: string): Promise<string> {
  if (!decksBucket) throw new ApiHttpError(500, 'configuration_error', 'The decks bucket is not configured.');
  const listed = await s3.send(new ListObjectsV2Command({ Bucket: decksBucket, Prefix: `quarantine/${uploadId}/` }));
  const keys = ((listed as { Contents?: Array<{ Key?: string }> }).Contents ?? []).flatMap(object => object.Key ? [object.Key] : []);
  if (keys.length > 0) return keys[0];
  // The upload id is server-generated and the filename has already passed the
  // request schema. This fallback keeps a just-uploaded object addressable when
  // S3 listing is eventually consistent, while StartExecution still receives a
  // key constrained to the upload prefix.
  return s3ObjectKey(uploadId, filename);
}

export const getJob: InstructorHandler = async (event, caller) => {
  if (!jobsTable) throw new ApiHttpError(500, 'configuration_error', 'The jobs table is not configured.');
  const jobId = pathParameter(event, 'jobId');
  const result = await ddb.send(new GetCommand({ TableName: jobsTable, Key: { jobId } }));
  if (!result.Item) throw new ApiHttpError(404, 'job_not_found', `No job exists for ${jobId}.`);
  const job = JobRecordSchema.safeParse(result.Item);
  if (!job.success) throw new Error(`Stored job ${jobId} does not match JobRecordSchema`);
  // Another instructor's job is indistinguishable from a missing one.
  if (job.data.ownerSub !== caller.sub) throw new ApiHttpError(404, 'job_not_found', `No job exists for ${jobId}.`);
  return respond(getJobRoute, {
    jobId: job.data.jobId,
    status: job.data.status,
    packId: job.data.packId,
    slides: job.data.slides,
    ...(job.data.error === undefined ? {} : { error: job.data.error }),
  });
};

export const listPackVersions: OperationHandler = async event => {
  if (!packsBucket) throw new ApiHttpError(500, 'configuration_error', 'The packs bucket is not configured.');
  const packId = pathParameter(event, 'packId');
  const listed = await s3.send(new ListObjectsV2Command({ Bucket: packsBucket, Prefix: `packs/${packId}/` }));
  const versions = (listed.Contents ?? []).flatMap(object => {
    const key = object.Key ?? '';
    const match = key.match(new RegExp(`^packs/${escapeRegExp(packId)}/(\\d+)\\.json$`, 'u'));
    if (!match || !object.LastModified) return [];
    const versionNumber = Number(match[1]);
    if (!Number.isSafeInteger(versionNumber) || versionNumber <= 0) return [];
    return [{
      version: versionNumber,
      publishedAt: object.LastModified.toISOString(),
      packUrl: `${assetBaseUrl}/packs/${encodeURIComponent(packId)}/${versionNumber}.json`,
    }];
  }).sort((a, b) => b.version - a.version);
  return respond(versionsRoute, { packId, versions });
};

export const getPack: OperationHandler = async event => {
  if (!packsBucket) throw new ApiHttpError(500, 'configuration_error', 'The packs bucket is not configured.');
  const packId = pathParameter(event, 'packId');
  const versionParameter = pathParameter(event, 'version');
  const packVersion = parsePositiveInteger(versionParameter, 'version');
  const key = `packs/${packId}/${packVersion}.json`;
  let object;
  try {
    object = await s3.send(new GetObjectCommand({ Bucket: packsBucket, Key: key }));
  } catch (error) {
    if (isNotFound(error)) throw new ApiHttpError(404, 'pack_not_found', `No published pack exists for ${packId} v${packVersion}.`);
    throw error;
  }
  if (!object.Body) throw new Error(`Pack object ${key} had no body`);
  const body = await object.Body.transformToString();
  let value: unknown;
  try { value = JSON.parse(body); } catch { throw new Error(`Pack object ${key} was not JSON`); }
  const pack = AccessPackSchema.safeParse(value);
  if (!pack.success) throw new Error(`Stored pack ${key} does not match AccessPackSchema`);
  return respond(packRoute, pack.data);
};

export const getArtifactManifest: OperationHandler = async event => {
  if (!artifactsBucket) throw new ApiHttpError(500, 'configuration_error', 'The artifacts bucket is not configured.');
  const artifactId = pathParameter(event, 'artifactId');
  const artifactVersion = parsePositiveInteger(pathParameter(event, 'artifactVersion'), 'artifactVersion');
  const key = `artifacts/${artifactId}/${artifactVersion}/manifest.json`;
  let object;
  try {
    object = await s3.send(new GetObjectCommand({ Bucket: artifactsBucket, Key: key }));
  } catch (error) {
    if (isNotFound(error)) throw new ApiHttpError(404, 'artifact_not_found', `No artifact manifest exists for ${artifactId} v${artifactVersion}.`);
    throw error;
  }
  if (!object.Body) throw new Error(`Artifact object ${key} had no body`);
  const body = await object.Body.transformToString();
  let value: unknown;
  try { value = JSON.parse(body); } catch { throw new Error(`Artifact object ${key} was not JSON`); }
  const manifest = ArtifactManifestSchema.safeParse(value);
  if (!manifest.success) throw new Error(`Stored artifact ${key} does not match ArtifactManifestSchema`);
  return respond(artifactRoute, manifest.data);
};

function parsePositiveInteger(value: string, name: string): number {
  if (!/^\d+$/u.test(value)) throw new ApiHttpError(400, 'invalid_path_parameter', `${name} must be a positive integer.`);
  const parsed = Number(value);
  if (!Number.isSafeInteger(parsed) || parsed <= 0) throw new ApiHttpError(400, 'invalid_path_parameter', `${name} must be a positive integer.`);
  return parsed;
}

function isNotFound(error: unknown): boolean {
  return typeof error === 'object' && error !== null && ('$metadata' in error || 'name' in error)
    && ((error as { name?: string }).name === 'NoSuchKey' || (error as { $metadata?: { httpStatusCode?: number } }).$metadata?.httpStatusCode === 404);
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/gu, '\\$&');
}
